## Artifical Neural Network

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#### Breast Cancer Dataset 

<img src="Images/Large14.jpg" width="300" height="60" />


Attribute Information:

1. Sample code number: id number
2. Clump Thickness: 1 - 10
3. Uniformity of Cell Size: 1 - 10
4. Uniformity of Cell Shape: 1 - 10
5. Marginal Adhesion: 1 - 10
6. Single Epithelial Cell Size: 1 - 10
7. Bare Nuclei: 1 - 10
8. Bland Chromatin: 1 - 10
9. Normal Nucleoli: 1 - 10
10. Mitoses: 1 - 10
11. Class: (2 for benign, 4 for malignant)

#### Data to csv

In [2]:
with open("breast-cancer-wisconsin.data") as f: #reading the data
    text = f.readlines()

In [3]:
## Data cleaning
breast_cancer = []
for l in text:
    breast_cancer.append(l.strip())

In [4]:
with open("breast_cancer.csv", "w") as f:
    f.write("ID_Num,Clump_Thickness,Cell_Size,Cell_Shape,"\
               "Marginal_Adhesion,Epithelial_Cell_Size,Bare_Nuclei,"\
               "Bland_Chromatin,Normal_Nucleoli,Mitoses,Class\n")
    for line in breast_cancer:
        f.write(line + "\n")
        

#### Data Preprocessing

In [5]:
dataset = pd.read_csv("breast_cancer.csv", na_values = '?')
#dataset = dataset.replace('?', np.nan)
#dataset = dataset.fillna(dataset.mean())
dataset = dataset.dropna()
X = dataset.iloc[:, 1:10].values #select all Except ID numbers and Class
Y = dataset.iloc[:, 10].values
Y = np.where(Y==2, 0, 1) #Class 2 for Benign = 0 else 1 (malignant)


In [6]:
dataset

ID_Num  Clump_Thickness  Cell_Size  Cell_Shape  Marginal_Adhesion  \
0    1000025                5          1           1                  1   
1    1002945                5          4           4                  5   
2    1015425                3          1           1                  1   
3    1016277                6          8           8                  1   
4    1017023                4          1           1                  3   
..       ...              ...        ...         ...                ...   
694   776715                3          1           1                  1   
695   841769                2          1           1                  1   
696   888820                5         10          10                  3   
697   897471                4          8           6                  4   
698   897471                4          8           8                  5   

     Epithelial_Cell_Size  Bare_Nuclei  Bland_Chromatin  Normal_Nucleoli  \
0                       2          1.0                3                1   
1                       7         10.0                3                2   
2                       2          2.0                3                1   
3                       3          4.0                3                7   
4                       2          1.0                3                1   
..                    ...          ...              ...              ...   
694                     3          2.0                1                1   
695                     2          1.0                1                1   
696                     7          3.0                8               10   
697                     3          4.0               10                6   
698                     4          5.0               10                4   

     Mitoses  Class  
0          1      2  
1          1      2  
2          1      2  
3          1      2  
4          1      2  
..       ...    ...  
694        1      2  
695        1      2  
696        2      4  
697        1      4  
698        1      4  

[683 rows x 11 columns]

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = .15, random_state=0)

In [9]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
X_train, 

(array([[ 1.9967197 ,  2.20519765,  0.93821373, ...,  0.22275834,
          0.01546113,  0.23858226],
        [-0.14064867, -0.69725614, -0.73613693, ..., -0.18353046,
         -0.6250714 , -0.33799154],
        [-1.20933285, -0.69725614, -0.73613693, ..., -0.99610807,
         -0.6250714 , -0.33799154],
        ...,
        [-1.20933285, -0.69725614, -0.73613693, ..., -0.99610807,
         -0.6250714 , -0.33799154],
        [-0.49687673, -0.69725614, -0.73613693, ..., -0.58981926,
         -0.6250714 , -0.33799154],
        [ 1.9967197 ,  1.88270278,  1.27308387, ...,  1.44162475,
          1.2965262 , -0.33799154]]),)

In [11]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


#### Artifical neural network with two hidden layers

<img src="Images/ANNDiagram.png" width="300" height="60" />


In [12]:
model = Sequential()

In [13]:
#First input layer and hidden layer
## Add picture of rectifier function


In [14]:
##Output layer is sigmoid function
#Stocastic gradient descent 

In [15]:
model.add(Dense(units = 5, kernel_initializer = 'uniform', activation = 'relu', input_dim = 9))

In [16]:
model.add(Dense(units = 5,  kernel_initializer = 'uniform', activation = 'relu'))

In [17]:
model.add(Dense(units = 1,  kernel_initializer = 'uniform', activation = 'sigmoid'))

In [18]:
#Stocastic gradient descent 
#Logarithmic Loss 235 of Udemy
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])



In [22]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 5)                 50        
_________________________________________________________________
dense_2 (Dense)              (None, 5)                 30        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 6         
Total params: 86
Trainable params: 86
Non-trainable params: 0
_________________________________________________________________


In [19]:
history = model.fit(X_train, y_train, batch_size = 5, epochs = 100, validation_data=(X_test, y_test))

Train on 580 samples, validate on 103 samples
Epoch 1/100
580/580 [==============================] - 2s 3ms/step - loss: 0.6699 - accuracy: 0.8052 - val_loss: 0.6094 - val_accuracy: 0.9515
Epoch 2/100
580/580 [==============================] - 0s 465us/step - loss: 0.4576 - accuracy: 0.9690 - val_loss: 0.3194 - val_accuracy: 0.9612
Epoch 3/100
580/580 [==============================] - 0s 410us/step - loss: 0.2111 - accuracy: 0.9707 - val_loss: 0.1639 - val_accuracy: 0.9515
Epoch 4/100
580/580 [==============================] - 0s 409us/step - loss: 0.1176 - accuracy: 0.9724 - val_loss: 0.1224 - val_accuracy: 0.9515
Epoch 5/100
580/580 [==============================] - 0s 393us/step - loss: 0.0929 - accuracy: 0.9724 - val_loss: 0.1090 - val_accuracy: 0.9515
Epoch 6/100
580/580 [==============================] - 0s 403us/step - loss: 0.0835 - accuracy: 0.9724 - val_loss: 0.1033 - val_accuracy: 0.9515
Epoch 7/100
580/580 [==============================] - 0s 383us/step - loss: 0.0796 - 

Epoch 57/100
580/580 [==============================] - 0s 424us/step - loss: 0.0656 - accuracy: 0.9793 - val_loss: 0.0757 - val_accuracy: 0.9709
Epoch 58/100
580/580 [==============================] - 0s 438us/step - loss: 0.0655 - accuracy: 0.9810 - val_loss: 0.0761 - val_accuracy: 0.9709
Epoch 59/100
580/580 [==============================] - 0s 436us/step - loss: 0.0657 - accuracy: 0.9810 - val_loss: 0.0759 - val_accuracy: 0.9709
Epoch 60/100
580/580 [==============================] - 0s 409us/step - loss: 0.0654 - accuracy: 0.9810 - val_loss: 0.0757 - val_accuracy: 0.9709
Epoch 61/100
580/580 [==============================] - 0s 402us/step - loss: 0.0658 - accuracy: 0.9793 - val_loss: 0.0748 - val_accuracy: 0.9709
Epoch 62/100
580/580 [==============================] - 0s 403us/step - loss: 0.0655 - accuracy: 0.9793 - val_loss: 0.0754 - val_accuracy: 0.9709
Epoch 63/100
580/580 [==============================] - 0s 397us/step - loss: 0.0653 - accuracy: 0.9793 - val_loss: 0.0751 -

From our results above, we were able to achieve 97% of validation score. 
I am fairly confident our model can accurately classify between a benign 
or malignant cases given a new data. 

In [20]:
X_train

array([[ 1.9967197 ,  2.20519765,  0.93821373, ...,  0.22275834,
         0.01546113,  0.23858226],
       [-0.14064867, -0.69725614, -0.73613693, ..., -0.18353046,
        -0.6250714 , -0.33799154],
       [-1.20933285, -0.69725614, -0.73613693, ..., -0.99610807,
        -0.6250714 , -0.33799154],
       ...,
       [-1.20933285, -0.69725614, -0.73613693, ..., -0.99610807,
        -0.6250714 , -0.33799154],
       [-0.49687673, -0.69725614, -0.73613693, ..., -0.58981926,
        -0.6250714 , -0.33799154],
       [ 1.9967197 ,  1.88270278,  1.27308387, ...,  1.44162475,
         1.2965262 , -0.33799154]])

In [21]:
y_train

array([1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,